baseurl = "https://jamesminton.com"
languageCode = "en-us"
# theme = "hugo-theme-stack"
paginate = 5
title = "James Minton"
disqusShortname = "hugo-theme-stack"            # Change it to your Disqus shortname before using
DefaultContentLanguage = "en"                  

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
    
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"
    [params.sidebar]
        emoji = ""
        avatar = "img/avatar.jpg"
        subtitle = "Designer | developer | Creative Director @<a href='https://www.hyperobjekt.com'>hyper0bjekt</a>"
    [params.article]
        math = false
        [params.article.license]
            enabled = false 
            default = ""
    [params.comments]
        enabled = false
        # Only Disqus is available so far
        provider = "disqus"
    [params.widgets]
        enabled = ['archives', 'tag-cloud']
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "archives"       
        [params.widgets.tagCloud]
            limit = 10
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
    [params.defaultImage]
        [params.defaultImage.article]
            enabled = false
            local = false
            src = ""
        [params.defaultImage.articleList]
            enabled = false
            local = true
            src = ""
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    # [[menu.main]]
    #    identifier = "about-cn"
    #    name = "About"
    #    url = "about"
    #    weight = -90
    #    pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives"
        weight = -70
        pre = "archives"

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    [markup.highlight]
        noClasses = false